spring:
  application:
    name: Dataflow Editor Server
  devtools:
    livereload:
      enabled: true

  #################
  ## JPA
  #################

  jpa:
    hibernate:
      ddl-auto: update
      use-new-id-generator-mappings: false
    generate-ddl: false
    show-sql: true
    properties:
      hibernate.hbm2ddl.import_files_sql_extractor: org.hibernate.tool.hbm2ddl.MultipleLinesSqlCommandExtractor
      hibernate.default_batch_fetch_size: ${chunkSize:1000}
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
    open-in-view: false
    #    database: mysql
    database: postgresql

  #################
  ## DataSource
  #################
  #  mysql jdbc config
  #  datasource:
  #    url: jdbc:log4jdbc:mysql://localhost:5432/test?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
  #    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
  #    username: root
  #    password: root
  #    sql-script-encoding: UTF-8
  #    continue-on-error: true
  #    initialization-mode: always
  #    hikari:
  #      connection-test-query: SELECT 1
  #      maximum-pool-size: 10
  #      max-lifetime: 1800000
  #      minimum-idle: 10
  #      idle-timeout: 600000

  # postgresql jdbc config
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
    sql-script-encoding: UTF-8
    continue-on-error: true
    initialization-mode: always
    hikari:
      connection-test-query: SELECT 1
      maximum-pool-size: 10
      max-lifetime: 1800000
      minimum-idle: 10
      idle-timeout: 600000

  #################
  ## Auto Configure
  #################

  autoconfigure:
    exclude:

  #################
  ## Freemarker
  #################

  freemarker:
    enabled: true
    prefix: /freemarker/
    template-loader-path: classpath:/templates
    suffix: .ftl


###################
## Web Container
###################

server:
  port: 8080
  address: 0.0.0.0



#################
## Application
#################

app:

#################
## Logging
#################

logging:
  config: src\main\resources\logback-local.xml
